export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const LIST_ROOM_BEGIN = "LIST_ROOM_BEGIN";
export const LIST_ROOM_SUCCESS = "LIST_ROOM_SUCCESS";
export const LIST_ROOM_ERROR = "LIST_ROOM_ERROR";

export const GET_MY_ROOMS_BEGIN = "GET_MY_ROOMS_BEGIN";
export const GET_MY_ROOMS_SUCCESS = "GET_MY_ROOMS_SUCCESS";

export const SET_EDIT_ROOM = "SET_EDIT_ROOM";

export const DELETE_ROOM_BEGIN = "DELETE_ROOM_BEGIN";

export const EDIT_ROOM_BEGIN = "EDIT_ROOM_BEGIN";
export const EDIT_ROOM_SUCCESS = "EDIT_ROOM_SUCCESS";
export const EDIT_ROOM_ERROR = "EDIT_ROOM_ERROR";

export const LIST_ROOMMATE_BEGIN = "LIST_ROOMMATE_BEGIN";
export const LIST_ROOMMATE_SUCCESS = "LIST_ROOMMATE_SUCCESS";
export const LIST_ROOMMATE_ERROR = "LIST_ROOMMATE_ERROR";

export const GET_MY_ROOMMATES_BEGIN = "GET_MY_ROOMMATES_BEGIN";
export const GET_MY_ROOMMATES_SUCCESS = "GET_MY_ROOMMATES_SUCCESS";

export const SET_EDIT_ROOMMATE = "SET_EDIT_ROOMMATE";

export const DELETE_ROOMMATE_BEGIN = "DELETE_ROOMMATE_BEGIN";

export const EDIT_ROOMMATE_BEGIN = "EDIT_ROOMMATE_BEGIN";
export const EDIT_ROOMMATE_SUCCESS = "EDIT_ROOMMATE_SUCCESS";
export const EDIT_ROOMMATE_ERROR = "EDIT_ROOMMATE_ERROR";

export const GET_ROOMS_BEGIN = "GET_ROOMS_BEGIN";
export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";

export const GET_ROOMMATES_BEGIN = "GET_ROOMMATES_BEGIN";
export const GET_ROOMMATES_SUCCESS = "GET_ROOMMATES_SUCCESS";

export const GET_SINGLE_ROOM_BEGIN = "GET_SINGLE_ROOM_BEGIN";
export const GET_SINGLE_ROOM_SUCCESS = "GET_SINGLE_ROOM_SUCCESS";

export const GET_SINGLE_ROOMMATE_BEGIN = "GET_SINGLE_ROOMMATE_BEGIN";
export const GET_SINGLE_ROOMMATE_SUCCESS = "GET_SINGLE_ROOMMATE_SUCCESS";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";
